version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn prettier-check
      - run: yarn
workflows:
  version: 2
  format_check_and_test_and_build_test:
    jobs:
      - build
      - test