name: CI

on:
  push:
    branches:
    - master

jobs:
  build-release:
    runs-on: macOS-10.14
    strategy:
      matrix:
        node-version: [11.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build-release
      run: |
        npm i -g yarn
        yarn
        yarn build
        yarn dist
    - uses: actions/upload-artifact@master
      with:
        name: build-release
        path: dist
