name: Quality Check

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: macOS-10.14
    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: test
      run: |
        npm i -g yarn
        yarn
        yarn test
  test-formatting:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: test formatting
      run: |
        npm i -g yarn
        yarn
        yarn prettier-check
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      run: |
        npm i -g yarn
        yarn
        yarn build
  e2e-test:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [11.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: |
            yarn install
          start: yarn web-start
          wait-on: http://localhost:1234
