name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  version-release:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build Release
      run: |
        npm i -g yarn
        yarn
        yarn build
        yarn dist
    - name: Zip Release
      run: zip -r build.zip ./dist
    - name: Make Release
      uses: softprops/action-gh-release@v1
      with:
        files: build.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
